In [62]:
import pandas as pd

#paths in my computer
datapath = 'Y:\\okofm\\tfl\\journey_data\\'

#paths at the university cluster
#datapath = 'Y:\\tfl\\journey_data\\data_random_sample_2012_2014.csv'

data = pd.read_csv(datapath+'data_random_sample_2012_2014.csv')

data

new_dates = []

for index, row in data.iterrows():
    if len(str(row['Start Date']))==19:
        new_dates.append(row['Start Date'][:-3])
    elif len(str(row['Start Date']))==16:
        new_dates.append(row['Start Date'])
    elif len(str(row['Start Date']))==3:
        new_dates.append(row['Start Date'])
        
        #print(row['Start Date'][:-3])

#new_dates
se = pd.Series(new_dates)
data['Start Date'] = se.values
data

data.dropna(axis=0, subset=['Start Date'], inplace=True)

#transform duration into minutes
data['Duration'] = data['Duration']/60

#adding day of the week, year, quarter, month, week, day, hour, minute
data['year'] = pd.to_datetime(data['Start Date'],format='%d/%m/%Y %H:%M').dt.year
data['quarter'] = pd.to_datetime(data['Start Date'],format='%d/%m/%Y %H:%M').dt.quarter
data['month'] = pd.to_datetime(data['Start Date'],format='%d/%m/%Y %H:%M').dt.month
data['week'] =  pd.to_datetime(data['Start Date'],format='%d/%m/%Y %H:%M').dt.week
data['day'] =  pd.to_datetime(data['Start Date'],format='%d/%m/%Y %H:%M').dt.day
data['hour'] =  pd.to_datetime(data['Start Date'],format='%d/%m/%Y %H:%M').dt.hour
data['minute'] =  pd.to_datetime(data['Start Date'],format='%d/%m/%Y %H:%M').dt.minute
data['day_of_week'] = pd.to_datetime(data['Start Date'],format='%d/%m/%Y %H:%M').dt.dayofweek
days = {0:'Mon',1:'Tues',2:'Weds',3:'Thurs',4:'Fri',5:'Sat',6:'Sun'}
data['day_of_week'] = data['day_of_week'].apply(lambda x: days[x])

data

,Unnamed: 0,Bike Id,Duration,End Date,EndStation Id,EndStation Name,Rental Id,Start Date,StartStation Id,StartStation Name,...,Unnamed: 11,Unnamed: 9,year,quarter,month,week,day,hour,minute,day_of_week
0,125436,11421.0,7.000000,28/11/2014 18:23,365.0,"City Road, Angel",39646767.0,28/11/2014 18:16,215.0,"Moorfields, Moorgate",...,NaN,NaN,2014,4,11,48,28,18,16,Fri
1,844777,8782.0,13.083333,31/10/2012 14:20,465.0,"Pitfield Street (North),Hoxton",17602913.0,31/10/2012 14:07,486.0,"Granby Street, Shoreditch",...,NaN,NaN,2012,4,10,44,31,14,7,Weds
2,475146,3903.0,15.816667,17/07/2012 07:03:49,122.0,"Norton Folgate, Liverpool Street",14020179.0,17/07/2012 06:47,173.0,"Waterloo Roundabout, Waterloo",...,NaN,NaN,2012,3,7,29,17,6,47,Tues
3,110869,705.0,8.000000,25/07/2014 10:07,583.0,"Abingdon Green, Great College Street",35470396.0,25/07/2014 09:59,243.0,"Gloucester Street, Pimlico",...,NaN,NaN,2014,3,7,30,25,9,59,Fri
4,35509,11907.0,11.000000,19/10/2014 19:43,393.0,"Snow Hill, Farringdon",38557830.0,19/10/2014 19:32,89.0,"Tavistock Place, Bloomsbury",...,NaN,NaN,2014,4,10,42,19,19,32,Sun
5,28814,5517.0,11.250000,16/09/2013 16:02,55.0,"Finsbury Circus, Liverpool Street",27512343.0,16/09/2013 15:51,174.0,"Strand, Strand",...,NaN,NaN,2013,3,9,38,16,15,51,Mon
6,283909,838.0,13.033333,12/11/2012 20:30,39.0,"Shoreditch High Street, Shoreditch",17902611.0,12/11/2012 20:17,23.0,"Red Lion Square, Holborn",...,NaN,NaN,2012,4,11,46,12,20,17,Mon
7,172715,7438.0,33.233333,15/06/2012 17:11:50,167.0,"Eccleston Place, Victoria",13046338.0,15/06/2012 16:38,109.0,"Soho Square , Soho",...,NaN,NaN,2012,2,6,24,15,16,38,Fri
8,610062,9401.0,17.000000,21/03/2014 08:44,100.0,"Albert Embankment, Vauxhall",31332688.0,21/03/2014 08:27,10.0,"Park Street, Bankside",...,NaN,NaN,2014,1,3,12,21,8,27,Fri
9,39230,8712.0,7.000000,06/05/2014 09:03,10.0,"Park Street, Bankside",32609135.0,06/05/2014 08:56,324.0,"Ontario Street, Elephant & Castle",...,NaN,NaN,2014,2,5,19,6,8,56,Tues
10,279717,6258.0,14.266667,06/06/2012 19:12:30,15.0,"Great Russell Street, Bloomsbury",12817065.0,06/06/2012 18:58,410.0,"Edgware Road Station, Paddington",...,NaN,NaN,2012,2,6,23,6,18,58,Weds
11,259228,10218.0,5.000000,07/07/2014 00:17,552.0,"Watney Street, Shadwell",34737010.0,07/07/2014 00:12,206.0,"New Road 1 , Whitechapel",...,NaN,NaN,2014,3,7,28,7,0,12,Mon
12,125454,5310.0,23.533333,06/12/2012 08:45,48.0,"Godliman Street, St. Paul's",18476550.0,06/12/2012 08:21,462.0,"Bonny Street, Camden Town",...,NaN,NaN,2012,4,12,49,6,8,21,Thurs
13,727433,6151.0,12.633333,28/03/2012 07:54,287.0,Bedford Way: Bloomsbury,11005191.0,28/03/2012 07:41,287.0,Bedford Way: Bloomsbury,...,NaN,NaN,2012,1,3,13,28,7,41,Weds
14,492680,2597.0,20.283333,29/12/2012 08:40,223.0,"Rodney Road , Walworth",18847789.0,29/12/2012 08:20,251.0,"Brushfield Street, Liverpool Street",...,NaN,NaN,2012,4,12,52,29,8,20,Sat
15,186371,4359.0,3.000000,26/06/2014 21:07,130.0,"Tower Gardens , Tower",34380802.0,26/06/2014 21:04,237.0,"Vaughan Way, Wapping",...,NaN,NaN,2014,2,6,26,26,21,4,Thurs
16,118628,215.0,6.000000,12/08/2014 19:48,640.0,"Silverthorne Road, Battersea",36232613.0,12/08/2014 19:42,602.0,"Union Grove, Wandsworth Road",...,NaN,NaN,2014,3,8,33,12,19,42,Tues
17,821953,1381.0,25.933333,24/09/2012 13:03,432.0,"Exhibition Road Museums, Knightsbridge",16564479.0,24/09/2012 12:37,424.0,"Ebury Bridge, Pimlico",...,NaN,NaN,2012,3,9,39,24,12,37,Mon
18,51525,8531.0,18.050000,07/04/2012 17:22:43,359.0,"Butler Place, Westminster",11290277.0,07/04/2012 17:04,191.0,"Hyde Park Corner, Hyde Park",...,NaN,NaN,2012,2,4,14,7,17,4,Sat
19,49331,420.0,35.666667,28/08/2012 15:09,309.0,"Embankment (Savoy), Strand",15624878.0,28/08/2012 14:33,85.0,"Tanner Street, Bermondsey",...,NaN,NaN,2012,3,8,35,28,14,33,Tues
20,69116,3633.0,6.000000,11/11/2014 16:15,732.0,"Duke Street Hill, London Bridge",39223422.0,11/11/2014 16:09,102.0,"Jewry Street, Aldgate",...,NaN,NaN,2014,4,11,46,11,16,9,Tues
21,32609,8536.0,13.000000,02/12/2013 20:35,14.0,"Belgrove Street , King's Cross",29239369.0,02/12/2013 20:22,240.0,"Colombo Street, Southwark",...,NaN,NaN,2013,4,12,49,2,20,22,Mon
22,543911,2395.0,23.916667,09/05/2012 13:57:32,112.0,"Stonecutter Street, Holborn",11961990.0,09/05/2012 13:33,109.0,"Soho Square , Soho",...,NaN,NaN,2012,2,5,19,9,13,33,Weds
23,13410,6359.0,13.000000,26/05/2013 19:09,61.0,"Great Dover Street, Borough",21757435.0,26/05/2013 18:56,273.0,"Belvedere Road, South Bank",...,NaN,NaN,2013,2,5,21,26,18,56,Sun
24,582310,8437.0,25.000000,08/05/2014 23:04,268.0,"Belgrave Road, Victoria",32685549.0,08/05/2014 22:39,160.0,"Waterloo Place, St. James's",...,NaN,NaN,2014,2,5,19,8,22,39,Thurs
25,58783,3779.0,24.000000,11/11/2014 09:09,204.0,"Margery Street, Clerkenwell",39212279.0,11/11/2014 08:45,200.0,"LMU Commercial Road, Whitechapel",...,NaN,NaN,2014,4,11,46,11,8,45,Tues
26,332342,4911.0,13.000000,02/05/2014 08:36,81.0,"Great Titchfield Street, Fitzrovia",32472708.0,02/05/2014 08:23,341.0,"Craven Street, Strand",...,NaN,NaN,2014,2,5,18,2,8,23,Fri
27,110176,689.0,14.000000,23/10/2013 16:48,154.0,"Waterloo Station 3, Waterloo",28446750.0,23/10/2013 16:34,20.0,"Drummond Street , Euston",...,NaN,NaN,2013,4,10,43,23,16,34,Weds
28,287727,8107.0,5.000000,25/11/2013 21:00,77.0,"Russell Square Station, Bloomsbury",29102469.0,25/11/2013 20:55,4.0,"St. Chad's Street, King's Cross",...,NaN,NaN,2013,4,11,48,25,20,55,Mon
29,740218,2883.0,22.316667,25/07/2012 20:46:34,499.0,"Furze Green, Bow",14321532.0,25/07/2012 20:24,458.0,"Wapping Lane 2, Wapping",...,NaN,NaN,2012,3,7,30,25,20,24,Weds
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
272910,65258,756.0,21.366667,25/06/2013 07:41,400.0,"George Street, Marylebone",22557341.0,25/06/2013 07:20,187.0,"Queen's Gate (South), South Kensington",...,NaN,NaN,2013,2,6,26,25,7,20,Tues
272911,150717,8432.0,53.683333,13/01/2013 03:14,304.0,"Cumberland Gate, Hyde Park",19121424.0,13/01/2013 02:20,111.0,"Park Lane , Hyde Park",...,NaN,NaN,2013,1,1,2,13,2,20,Sun
272912,160409,11319.0,19.000000,05/02/2014 09:22,22.0,"Northington Street , Holborn",30318814.0,05/02/2014 09:03,104.0,"Crosswall, Tower",...,NaN,NaN,2014,1,2,6,5,9,3,Weds
272913,283581,2507.0,50.000000,25/12/2013 13:23,492.0,"The Green Bridge, Mile End",29610978.0,25/12/2013 12:33,222.0,"Knightsbridge, Hyde Park",...,NaN,NaN,2013,4,12,52,25,12,33,Weds
272914,248972,80.0,30.750000,07/09/2012 12:39,407.0,"Speakers' Corner 1, Hyde Park",15985869.0,07/09/2012 12:09,157.0,"Wright's Lane, Kensington",...,NaN,NaN,2012,3,9,36,7,12,9,Fri
272915,125138,9669.0,2.000000,29/12/2013 11:43,266.0,"Queen's Gate (North), Kensington",29670353.0,29/12/2013 11:41,97.0,"Gloucester Road (North), Kensington",...,NaN,NaN,2013,4,12,52,29,11,41,Sun
272916,205379,9655.0,11.000000,02/12/2013 17:33,374.0,"Waterloo Station 1, Waterloo",29233875.0,02/12/2013 17:22,393.0,"Snow Hill, Farringdon",...,NaN,NaN,2013,4,12,49,2,17,22,Mon
272917,326839,10452.0,7.000000,26/07/2014 16:39,13.0,"Scala Street, Fitzrovia",35520277.0,26/07/2014 16:32,313.0,"Wells Street, Fitzrovia",...,NaN,NaN,2014,3,7,30,26,16,32,Sat
272918,613218,64.0,37.816667,11/07/2013 13:43,167.0,"Eccleston Place, Victoria",23061084.0,11/07/2013 13:05,153.0,"Bayswater Road, Hyde Park",...,NaN,NaN,2013,3,7,28,11,13,5,Thurs
272920,33861,6246.0,7.000000,29/07/2014 08:01,572.0,"Greenland Road, Camden Town",35624821.0,29/07/2014 07:54,34.0,"Pancras Road, King's Cross",...,NaN,NaN,2014,3,7,31,29,7,54,Tues
272921,458115,8090.0,10.450000,05/06/2013 07:22,486.0,"Granby Street, Shoreditch",22032058.0,05/06/2013 07:12,319.0,"Baldwin Street, St. Luke's",...,NaN,NaN,2013,2,6,23,5,7,12,Weds
272922,79466,10931.0,6.000000,12/08/2014 09:24,272.0,"Baylis Road, Waterloo",36208902.0,12/08/2014 09:18,310.0,"Black Prince Road, Vauxhall",...,NaN,NaN,2014,3,8,33,12,9,18,Tues
272923,238653,5737.0,25.100000,27/04/2012 18:41:20,559.0,"Abbotsbury Road, Holland Park",11710909.0,27/04/2012 18:16,398.0,"Holland Walk, Kensington",...,NaN,NaN,2012,2,4,17,27,18,16,Fri
272924,113594,8063.0,16.483333,19/07/2012 19:34:15,329.0,"Prince Albert Road, Regent's Park",14074546.0,19/07/2012 19:17,47.0,"Warwick Avenue Station, Maida Vale",...,NaN,NaN,2012,3,7,29,19,19,17,Thurs
272925,28066,2372.0,21.666667,16/09/2013 15:00,314.0,"Tyers Gate, Bermondsey",27511522.0,16/09/2013 14:38,281.0,"Smith Square, Westminster",...,NaN,NaN,2013,3,9,38,16,14,38,Mon
272926,283319,2824.0,18.633333,30/08/2013 06:27,228.0,"St. James's Square, St. James's",24583017.0,30/08/2013 06:08,573.0,"Limerston Street, Chelsea",...,NaN,NaN,2013,3,8,35,30,6,8,Fri
272927,74408,3479.0,7.000000,10/06/2013 18:05,24.0,"British Museum, Bloomsbury",22156150.0,10/06/2013 17:58,311.0,"Foley Street, Fitzrovia",...,NaN,NaN,2013,2,6,24,10,17,58,Mon
272928,734397,3914.0,22.000000,18/05/2014 02:02,64.0,"William IV Street, Strand",32964572.0,18/05/2014 01:40,132.0,"Bethnal Green Road, Shoreditch",...,NaN,NaN,2014,2,5,20,18,1,40,Sun
272929,208673,8027.0,7.300000,24/09/2013 14:43,221.0,"Horseferry Road, Westminster",27710597.0,24/09/2013 14:36,177.0,"Ashley Place, Victoria",...,NaN,NaN,2013,3,9,39,24,14,36,Tues
272930,301479,8107.0,10.216667,19/02/2013 09:06,193.0,"Bankside Mix, Bankside",19781131.0,19/02/2013 08:56,509.0,"Fore Street, Guildhall",...,NaN,NaN,2013,1,2,8,19,8,56,Tues
272931,370810,7621.0,26.200000,12/05/2013 11:25,248.0,"Triangle Car Park, Hyde Park",21430868.0,12/05/2013 10:59,384.0,"Marloes Road, Kensington",...,NaN,NaN,2013,2,5,19,12,10,59,Sun
272932,127286,3507.0,10.550000,11/01/2013 16:42,338.0,"Wellington Street , Strand",19077971.0,11/01/2013 16:31,387.0,"Fire Brigade Pier, Vauxhall",...,NaN,NaN,2013,1,1,2,11,16,31,Fri
272933,407466,6901.0,14.000000,28/01/2013 18:59,513.0,"Watney Market, Stepney",19361321.0,28/01/2013 18:45,464.0,"St. Mary and St. Michael Church, Stepney",...,NaN,NaN,2013,1,1,5,28,18,45,Mon
272934,377661,12221.0,17.000000,08/03/2014 07:43,379.0,"Turquoise Island, Notting Hill",30949891.0,08/03/2014 07:26,268.0,"Belgrave Road, Victoria",...,NaN,NaN,2014,1,3,10,8,7,26,Sat
272935,311946,5842.0,11.533333,27/05/2012 07:48:20,193.0,"Bankside Mix, Bankside",12513053.0,27/05/2012 07:36,298.0,"Curlew Street, Shad Thames",...,NaN,NaN,2012,2,5,21,27,7,36,Sun
272936,485956,4791.0,89.000000,03/05/2014 15:12,334.0,"Concert Hall Approach 1, South Bank",32507549.0,03/05/2014 13:43,334.0,"Concert Hall Approach 1, South Bank",...,NaN,NaN,2014,2,5,18,3,13,43,Sat
272937,369739,1993.0,6.850000,22/02/2013 13:21,174.0,"Strand, Strand",19857585.0,22/02/2013 13:14,154.0,"Waterloo Station 3, Waterloo",...,NaN,NaN,2013,1,2,8,22,13,14,Fri
272938,12441,2523.0,13.333333,29/02/2012 17:38,174.0,Strand: Strand,10293345.0,29/02/2012 17:25,11.0,Brunswick Square: Bloomsbury,...,NaN,NaN,2012,1,2,9,29,17,25,Weds
272939,304251,3371.0,22.000000,18/06/2014 09:08,509.0,"Fore Street, Guildhall",34029118.0,18/06/2014 08:46,267.0,"Regency Street, Westminster",...,NaN,NaN,2014,2,6,25,18,8,46,Weds
272940,380508,7996.0,68.000000,25/05/2014 13:04,191.0,"Hyde Park Corner, Hyde Park",33211369.0,25/05/2014 11:56,350.0,"Queen's Gate, Kensington Gardens",...,NaN,NaN,2014,2,5,21,25,11,56,Sun

In [109]:
#checking number of stations matches
print(len(data['StartStation Id'].unique()))
print(len(data['EndStation Id'].unique()))

763
762

In [100]:
#getting number of journeys by start and end station
journey_counts = data.groupby(['StartStation Id','EndStation Id']).count()
columns_to_drop = journey_counts.columns
journey_counts['Number of Journeys'] = journey_counts['Unnamed: 0']
journey_counts.drop(columns_to_drop, axis=1, inplace=True)
journey_counts

                               Number of Journeys
StartStation Id EndStation Id
1.0             0.0                             1
                1.0                            13
                4.0                             2
                6.0                             1
                11.0                            5
                12.0                            4
                14.0                            5
                15.0                            2
                16.0                            1
                17.0                            2
                18.0                            1
                20.0                            1
                22.0                            1
                23.0                            1
                24.0                            3
                31.0                            1
                34.0                            1
                39.0                            1
                40.0                            1
                41.0                            3
                42.0                            3
                46.0                            1
                50.0                            1
                51.0                            1
                52.0                            1
                54.0                            5
                57.0                            8
                58.0                            1
                61.0                            1
                63.0                            3
...                                           ...
775.0           730.0                           1
                746.0                           1
                775.0                           1
776.0           251.0                           1
                432.0                           1
                558.0                           1
                609.0                           1
                636.0                           1
                637.0                           1
                651.0                           1
                664.0                           1
                673.0                           1
                676.0                           1
                766.0                           1
777.0           14.0                            1
                194.0                           1
                218.0                           1
                618.0                           1
                777.0                           1
778.0           132.0                           1
                206.0                           1
                577.0                           1
                717.0                           1
                721.0                           1
                778.0                           1
1066.0          0.0                             1
1071.0          0.0                             1
2696.0          0.0                             1
200042.0        0.0                             1
200080.0        434.0                           1

[104926 rows x 1 columns]

In [111]:
#number of total journeys starting at each station
journey_total = journey_counts.groupby(level=0).sum()
journey_total

                 Number of Journeys
StartStation Id
1.0                             279
2.0                             339
3.0                             350
4.0                             496
5.0                             410
6.0                             441
7.0                             198
8.0                              58
9.0                             515
10.0                            360
11.0                            532
12.0                            980
13.0                            330
14.0                           2584
15.0                            566
16.0                            626
17.0                            839
18.0                            980
19.0                            637
20.0                            520
21.0                            161
22.0                            570
23.0                            398
24.0                            759
25.0                            575
26.0                            397
27.0                            510
28.0                            651
29.0                            344
30.0                            391
...                             ...
754.0                            26
755.0                           126
756.0                            73
757.0                            80
758.0                           100
759.0                            43
760.0                            58
761.0                            66
762.0                           213
763.0                            49
764.0                            44
765.0                            24
766.0                            41
767.0                            10
768.0                            31
769.0                            56
770.0                            31
771.0                            13
772.0                            54
773.0                            74
774.0                            20
775.0                            27
776.0                            11
777.0                             5
778.0                             6
1066.0                            1
1071.0                            1
2696.0                            1
200042.0                          1
200080.0                          1

[763 rows x 1 columns]

In [115]:
#getting the probabilities
journey_prob = journey_counts.merge(journey_total, how='inner', left_index='StartStation Id', right_index='StartStation Id')
journey_prob['Probability'] = journey_prob['Number of Journeys_x']/journey_prob['Number of Journeys_y']
journey_prob

                               Number of Journeys_x  Number of Journeys_y  \
StartStation Id EndStation Id
1.0             0.0                               1                   279
                1.0                              13                   279
                4.0                               2                   279
                6.0                               1                   279
                11.0                              5                   279
                12.0                              4                   279
                14.0                              5                   279
                15.0                              2                   279
                16.0                              1                   279
                17.0                              2                   279
                18.0                              1                   279
                20.0                              1                   279
                22.0                              1                   279
                23.0                              1                   279
                24.0                              3                   279
                31.0                              1                   279
                34.0                              1                   279
                39.0                              1                   279
                40.0                              1                   279
                41.0                              3                   279
                42.0                              3                   279
                46.0                              1                   279
                50.0                              1                   279
                51.0                              1                   279
                52.0                              1                   279
                54.0                              5                   279
                57.0                              8                   279
                58.0                              1                   279
                61.0                              1                   279
                63.0                              3                   279
...                                             ...                   ...
775.0           730.0                             1                    27
                746.0                             1                    27
                775.0                             1                    27
776.0           251.0                             1                    11
                432.0                             1                    11
                558.0                             1                    11
                609.0                             1                    11
                636.0                             1                    11
                637.0                             1                    11
                651.0                             1                    11
                664.0                             1                    11
                673.0                             1                    11
                676.0                             1                    11
                766.0                             1                    11
777.0           14.0                              1                     5
                194.0                             1                     5
                218.0                             1                     5
                618.0                             1                     5
                777.0                             1                     5
778.0           132.0                             1                     6
                206.0                             1                     6
                577.0                             1                     6
                717.0                             1                     6
                721.0                             1                     6
                778.0                             1                     6
1066.0          0.0                               1                     1
1071.0          0.0                               1                     1
2696.0          0.0                               1                     1
200042.0        0.0                               1                     1
200080.0        434.0                             1                     1

                               Probability
StartStation Id EndStation Id
1.0             0.0               0.003584
                1.0               0.046595
                4.0               0.007168
                6.0               0.003584
                11.0              0.017921
                12.0              0.014337
                14.0              0.017921
                15.0              0.007168
                16.0              0.003584
                17.0              0.007168
                18.0              0.003584
                20.0              0.003584
                22.0              0.003584
                23.0              0.003584
                24.0              0.010753
                31.0              0.003584
                34.0              0.003584
                39.0              0.003584
                40.0              0.003584
                41.0              0.010753
                42.0              0.010753
                46.0              0.003584
                50.0              0.003584
                51.0              0.003584
                52.0              0.003584
                54.0              0.017921
                57.0              0.028674
                58.0              0.003584
                61.0              0.003584
                63.0              0.010753
...                                    ...
775.0           730.0             0.037037
                746.0             0.037037
                775.0             0.037037
776.0           251.0             0.090909
                432.0             0.090909
                558.0             0.090909
                609.0             0.090909
                636.0             0.090909
                637.0             0.090909
                651.0             0.090909
                664.0             0.090909
                673.0             0.090909
                676.0             0.090909
                766.0             0.090909
777.0           14.0              0.200000
                194.0             0.200000
                218.0             0.200000
                618.0             0.200000
                777.0             0.200000
778.0           132.0             0.166667
                206.0             0.166667
                577.0             0.166667
                717.0             0.166667
                721.0             0.166667
                778.0             0.166667
1066.0          0.0               1.000000
1071.0          0.0               1.000000
2696.0          0.0               1.000000
200042.0        0.0               1.000000
200080.0        434.0             1.000000

[104926 rows x 3 columns]

In [116]:
#checking they add to 1
journey_prob['Probability'].groupby(level=0).sum()

StartStation Id
1.0         1.0
2.0         1.0
3.0         1.0
4.0         1.0
5.0         1.0
6.0         1.0
7.0         1.0
8.0         1.0
9.0         1.0
10.0        1.0
11.0        1.0
12.0        1.0
13.0        1.0
14.0        1.0
15.0        1.0
16.0        1.0
17.0        1.0
18.0        1.0
19.0        1.0
20.0        1.0
21.0        1.0
22.0        1.0
23.0        1.0
24.0        1.0
25.0        1.0
26.0        1.0
27.0        1.0
28.0        1.0
29.0        1.0
30.0        1.0
           ...
754.0       1.0
755.0       1.0
756.0       1.0
757.0       1.0
758.0       1.0
759.0       1.0
760.0       1.0
761.0       1.0
762.0       1.0
763.0       1.0
764.0       1.0
765.0       1.0
766.0       1.0
767.0       1.0
768.0       1.0
769.0       1.0
770.0       1.0
771.0       1.0
772.0       1.0
773.0       1.0
774.0       1.0
775.0       1.0
776.0       1.0
777.0       1.0
778.0       1.0
1066.0      1.0
1071.0      1.0
2696.0      1.0
200042.0    1.0
200080.0    1.0
Name: Probability, dtype: float64

In [117]:
journey_prob = journey_prob['Probability']
journey_prob

StartStation Id  EndStation Id
1.0              0.0              0.003584
                 1.0              0.046595
                 4.0              0.007168
                 6.0              0.003584
                 11.0             0.017921
                 12.0             0.014337
                 14.0             0.017921
                 15.0             0.007168
                 16.0             0.003584
                 17.0             0.007168
                 18.0             0.003584
                 20.0             0.003584
                 22.0             0.003584
                 23.0             0.003584
                 24.0             0.010753
                 31.0             0.003584
                 34.0             0.003584
                 39.0             0.003584
                 40.0             0.003584
                 41.0             0.010753
                 42.0             0.010753
                 46.0             0.003584
                 50.0             0.003584
                 51.0             0.003584
                 52.0             0.003584
                 54.0             0.017921
                 57.0             0.028674
                 58.0             0.003584
                 61.0             0.003584
                 63.0             0.010753
                                    ...
775.0            730.0            0.037037
                 746.0            0.037037
                 775.0            0.037037
776.0            251.0            0.090909
                 432.0            0.090909
                 558.0            0.090909
                 609.0            0.090909
                 636.0            0.090909
                 637.0            0.090909
                 651.0            0.090909
                 664.0            0.090909
                 673.0            0.090909
                 676.0            0.090909
                 766.0            0.090909
777.0            14.0             0.200000
                 194.0            0.200000
                 218.0            0.200000
                 618.0            0.200000
                 777.0            0.200000
778.0            132.0            0.166667
                 206.0            0.166667
                 577.0            0.166667
                 717.0            0.166667
                 721.0            0.166667
                 778.0            0.166667
1066.0           0.0              1.000000
1071.0           0.0              1.000000
2696.0           0.0              1.000000
200042.0         0.0              1.000000
200080.0         434.0            1.000000
Name: Probability, dtype: float64

In [127]:
prob_matrix = journey_prob.unstack()

In [128]:
prob_matrix.fillna(0, inplace=True)
prob_matrix

EndStation Id,0.0,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,...,769.0,770.0,771.0,772.0,773.0,774.0,775.0,776.0,777.0,778.0
StartStation Id,,,,,,,,,,,,,,,,,,,,,
1.0,0.003584,0.046595,0.000000,0.000000,0.007168,0.000000,0.003584,0.000000,0.000000,0.000000,...,0.000000,0.00,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.000000
2.0,0.008850,0.000000,0.023599,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.00,0.00295,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.000000
3.0,0.005714,0.002857,0.000000,0.008571,0.002857,0.000000,0.000000,0.000000,0.000000,0.002857,...,0.000000,0.00,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.000000
4.0,0.006048,0.002016,0.000000,0.000000,0.012097,0.000000,0.002016,0.000000,0.000000,0.008065,...,0.000000,0.00,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.000000
5.0,0.002439,0.000000,0.000000,0.000000,0.000000,0.029268,0.000000,0.000000,0.002439,0.000000,...,0.004878,0.00,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.000000
6.0,0.011338,0.000000,0.000000,0.000000,0.002268,0.000000,0.006803,0.002268,0.002268,0.000000,...,0.000000,0.00,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.000000
7.0,0.025253,0.000000,0.005051,0.000000,0.000000,0.000000,0.000000,0.065657,0.005051,0.000000,...,0.000000,0.00,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.000000
8.0,0.017241,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.017241,0.000000,...,0.000000,0.00,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.000000
9.0,0.003883,0.000000,0.000000,0.000000,0.001942,0.000000,0.000000,0.000000,0.000000,0.019417,...,0.000000,0.00,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.000000
10.0,0.011111,0.000000,0.000000,0.000000,0.008333,0.000000,0.000000,0.000000,0.000000,0.016667,...,0.000000,0.00,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.000000
11.0,0.001880,0.000000,0.001880,0.000000,0.011278,0.000000,0.001880,0.000000,0.000000,0.000000,...,0.000000,0.00,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.000000
12.0,0.011224,0.001020,0.001020,0.001020,0.012245,0.000000,0.002041,0.001020,0.001020,0.001020,...,0.000000,0.00,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.000000
13.0,0.006061,0.003030,0.000000,0.003030,0.000000,0.000000,0.009091,0.000000,0.000000,0.000000,...,0.000000,0.00,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.000000
14.0,0.005805,0.001161,0.000000,0.001548,0.001935,0.000387,0.005031,0.000000,0.000000,0.001161,...,0.000000,0.00,0.00000,0.000000,0.001161,0.00000,0.000387,0.000000,0.0,0.000000
15.0,0.012367,0.000000,0.000000,0.000000,0.005300,0.000000,0.001767,0.000000,0.000000,0.003534,...,0.000000,0.00,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.000000
16.0,0.014377,0.000000,0.000000,0.000000,0.001597,0.000000,0.004792,0.000000,0.000000,0.001597,...,0.000000,0.00,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.000000
17.0,0.015495,0.000000,0.000000,0.001192,0.014303,0.000000,0.003576,0.000000,0.000000,0.001192,...,0.000000,0.00,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.000000
18.0,0.010204,0.003061,0.000000,0.000000,0.004082,0.001020,0.003061,0.000000,0.000000,0.003061,...,0.000000,0.00,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.000000
19.0,0.004710,0.000000,0.000000,0.000000,0.004710,0.000000,0.001570,0.000000,0.000000,0.000000,...,0.000000,0.00,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.000000
20.0,0.003846,0.000000,0.000000,0.000000,0.000000,0.000000,0.007692,0.003846,0.000000,0.003846,...,0.000000,0.00,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.000000
21.0,0.006211,0.000000,0.000000,0.000000,0.000000,0.000000,0.006211,0.000000,0.000000,0.000000,...,0.000000,0.00,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.000000
22.0,0.007018,0.001754,0.000000,0.001754,0.019298,0.000000,0.001754,0.001754,0.000000,0.000000,...,0.000000,0.00,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.000000
23.0,0.007538,0.005025,0.000000,0.005025,0.005025,0.000000,0.002513,0.000000,0.000000,0.000000,...,0.000000,0.00,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.000000
24.0,0.006588,0.003953,0.000000,0.000000,0.013175,0.002635,0.002635,0.000000,0.000000,0.001318,...,0.000000,0.00,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.000000
25.0,0.003478,0.000000,0.000000,0.000000,0.000000,0.000000,0.005217,0.000000,0.000000,0.001739,...,0.000000,0.00,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.000000
26.0,0.005038,0.000000,0.000000,0.005038,0.010076,0.000000,0.005038,0.000000,0.000000,0.002519,...,0.000000,0.00,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.000000
27.0,0.005882,0.000000,0.000000,0.000000,0.009804,0.003922,0.003922,0.000000,0.000000,0.000000,...,0.000000,0.00,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.000000
28.0,0.010753,0.000000,0.000000,0.000000,0.001536,0.000000,0.010753,0.001536,0.000000,0.000000,...,0.000000,0.00,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.000000
29.0,0.005814,0.000000,0.002907,0.000000,0.000000,0.005814,0.000000,0.000000,0.000000,0.000000,...,0.002907,0.00,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.000000
30.0,0.002558,0.002558,0.000000,0.005115,0.002558,0.000000,0.000000,0.000000,0.000000,0.005115,...,0.000000,0.00,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
754.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.00,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.000000
755.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.00,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.000000
756.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.041096,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.00,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.000000
757.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.012500,0.000000,0.000000,0.000000,...,0.000000,0.00,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.000000
758.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.00,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.000000
759.0,0.000000,0.000000,0.046512,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.00,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.000000
760.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.017241,0.000000,0.000000,0.000000,...,0.000000,0.00,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.000000
761.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.00,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.000000
762.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.00,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.000000
763.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.00,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.000000
764.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.00,0.00000,0.000000,0.000000,0.00000,0.000000,0.022727,0.0,0.000000
765.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.00,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.000000
766.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.00,0.00000,0.000000,0.000000,0.02439,0.000000,0.000000,0.0,0.000000
767.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.00,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.000000
768.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.032258,0.000000,0.000000,0.000000,0.000000,...,0.032258,0.00,0.00000,0.000000,0.000000,0.00000,0.000000,0.064516,0.0,0.000000
769.0,0.000000,0.000000,0.017857,0.000000,0.000000,0.017857,0.000000,0.000000,0.000000,0.000000,...,0.053571,0.00,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.000000
770.0,0.000000,0.000000,0.032258,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.00,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.000000
771.0,0.000000,0.000000,0.076923,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.00,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.000000
772.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.00,0.00000,0.037037,0.000000,0.00000,0.000000,0.000000,0.0,0.000000
773.0,0.000000,0.000000,0.000000,0.000000,0.013514,0.000000,0.013514,0.000000,0.000000,0.000000,...,0.000000,0.00,0.00000,0.000000,0.027027,0.00000,0.000000,0.000000,0.0,0.000000
774.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.05,0.00000,0.000000,0.000000,0.15000,0.000000,0.000000,0.0,0.000000
775.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.00,0.00000,0.000000,0.000000,0.00000,0.037037,0.000000,0.0,0.000000
776.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.00,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.000000
777.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.00,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.2,0.000000
778.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.00,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.166667
1066.0,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.00,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.000000
1071.0,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.00,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.000000
2696.0,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.00,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.000000
200042.0,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.00,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.000000
200080.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.00,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.000000