In [1]:
import pandas as pd

datapath_2012 = 'Y:\\okofm\\tfl\\journey_data\\cyclehireusagestats-2012\\'
datapath_2013 = 'Y:\\okofm\\tfl\\journey_data\\cyclehireusagestats-2013\\'
datapath_2014 = 'Y:\\okofm\\tfl\\journey_data\\cyclehireusagestats-2014\\'

data1 = pd.read_csv(datapath_2013 + '1. Journey Data Extract 01Jan-05Jan13.csv')

data1

,Rental Id,Duration,Bike Id,End Date,EndStation Id,EndStation Name,Start Date,StartStation Id,StartStation Name
0,18884041,271,4313.0,02/01/2013 13:32,251,"Brushfield Street, Liverpool Street",02/01/2013 13:28,509,"Fore Street, Guildhall"
1,18905547,364,7755.0,03/01/2013 17:19,251,"Brushfield Street, Liverpool Street",03/01/2013 17:13,509,"Fore Street, Guildhall"
2,18941512,372,1193.0,04/01/2013 16:26,251,"Brushfield Street, Liverpool Street",04/01/2013 16:20,509,"Fore Street, Guildhall"
3,18940395,1606,7163.0,04/01/2013 08:36,368,"Harriet Street, Knightsbridge",04/01/2013 08:10,62,"Cotton Garden Estate, Kennington"
4,18944057,1352,4423.0,05/01/2013 16:58,386,"Moor Street, Soho",05/01/2013 16:36,144,"Kennington Cross, Kennington"
5,18869989,1646,161.0,01/01/2013 11:51,329,"Prince Albert Road, Regent's Park",01/01/2013 11:24,326,"Graham Street, Angel"
6,18873706,694,1673.0,01/01/2013 18:10,45,"Harewood Avenue, Marylebone",01/01/2013 17:59,116,"Little Argyll Street, West End"
7,18925527,737,2799.0,04/01/2013 18:28,196,"Union Street, The Borough",04/01/2013 18:16,156,"New Kent Road, Borough"
8,18944247,349,4124.0,05/01/2013 15:48,196,"Union Street, The Borough",05/01/2013 15:42,156,"New Kent Road, Borough"
9,18945866,1679,7398.0,05/01/2013 17:57,2,"Phillimore Gardens, Kensington",05/01/2013 17:29,386,"Moor Street, Soho"
10,18886658,378,6576.0,02/01/2013 19:07,196,"Union Street, The Borough",02/01/2013 19:01,156,"New Kent Road, Borough"
11,18877625,1081,8124.0,01/01/2013 18:17,144,"Kennington Cross, Kennington",01/01/2013 17:59,116,"Little Argyll Street, West End"
12,18879619,1077,7585.0,01/01/2013 11:54,159,"Great Marlborough Street, Soho",01/01/2013 11:36,86,"Sancroft Street, Vauxhall"
13,18886440,857,4329.0,02/01/2013 08:25,159,"Great Marlborough Street, Soho",02/01/2013 08:11,86,"Sancroft Street, Vauxhall"
14,18946752,818,861.0,05/01/2013 10:54,159,"Great Marlborough Street, Soho",05/01/2013 10:40,86,"Sancroft Street, Vauxhall"
15,18905623,893,5625.0,03/01/2013 08:24,159,"Great Marlborough Street, Soho",03/01/2013 08:09,86,"Sancroft Street, Vauxhall"
16,18919033,1136,6849.0,03/01/2013 13:04,305,"Kennington Lane Tesco, Vauxhall",03/01/2013 12:46,159,"Great Marlborough Street, Soho"
17,18937761,932,8587.0,04/01/2013 08:23,159,"Great Marlborough Street, Soho",04/01/2013 08:08,86,"Sancroft Street, Vauxhall"
18,18922728,2011,7554.0,04/01/2013 18:00,2,"Phillimore Gardens, Kensington",04/01/2013 17:27,225,"Notting Hill Gate Station, Notting Hill"
19,18872324,672,6608.0,01/01/2013 06:49,546,"New Fetter Lane, Holborn",01/01/2013 06:38,295,"Swan Street, The Borough"
20,18892341,672,4492.0,02/01/2013 07:02,546,"New Fetter Lane, Holborn",02/01/2013 06:51,295,"Swan Street, The Borough"
21,18903687,692,3552.0,03/01/2013 06:48,546,"New Fetter Lane, Holborn",03/01/2013 06:36,295,"Swan Street, The Borough"
22,18921196,746,842.0,04/01/2013 06:54,546,"New Fetter Lane, Holborn",04/01/2013 06:41,295,"Swan Street, The Borough"
23,18919901,987,3202.0,04/01/2013 15:25,194,"Hop Exchange, The Borough",04/01/2013 15:09,386,"Moor Street, Soho"
24,18895284,498,671.0,02/01/2013 17:25,326,"Graham Street, Angel",02/01/2013 17:17,227,"Great Percy Street, Clerkenwell"
25,18928454,518,2510.0,04/01/2013 13:41,67,"Hatton Garden, Holborn",04/01/2013 13:32,42,"Wenlock Road , Hoxton"
26,18882692,352,1503.0,02/01/2013 07:52,101,"Queen Street, Bank",02/01/2013 07:46,78,"Sadlers Sports Centre, Finsbury"
27,18905226,370,3464.0,03/01/2013 08:05,101,"Queen Street, Bank",03/01/2013 07:59,78,"Sadlers Sports Centre, Finsbury"
28,18928163,717,4341.0,04/01/2013 08:10,101,"Queen Street, Bank",04/01/2013 07:58,107,"Finsbury Leisure Centre, St. Luke's"
29,18921055,1083,7672.0,04/01/2013 15:49,213,"Wellington Arch, Hyde Park",04/01/2013 15:31,133,"Derry Street, Kensington"
...,...,...,...,...,...,...,...,...,...
88269,18912322,1883,7383.0,03/01/2013 19:40,301,"Marylebone Lane, Marylebone",03/01/2013 19:09,217,"Wormwood Street, Liverpool Street"
88270,18897326,570,5010.0,02/01/2013 07:38,221,"Horseferry Road, Westminster",02/01/2013 07:29,154,"Waterloo Station 3, Waterloo"
88271,18910878,467,1174.0,03/01/2013 07:37,221,"Horseferry Road, Westminster",03/01/2013 07:29,154,"Waterloo Station 3, Waterloo"
88272,18936827,535,7375.0,04/01/2013 07:26,221,"Horseferry Road, Westminster",04/01/2013 07:18,154,"Waterloo Station 3, Waterloo"
88273,18886255,601,8858.0,02/01/2013 19:40,161,"Guildhouse Street, Victoria",02/01/2013 19:30,233,"Pall Mall East, West End"
88274,18910065,602,833.0,03/01/2013 08:16,95,"Aldersgate Street, Barbican",03/01/2013 08:06,154,"Waterloo Station 3, Waterloo"
88275,18940128,662,3258.0,04/01/2013 08:31,52,"Roscoe Street, St. Luke's",04/01/2013 08:20,154,"Waterloo Station 3, Waterloo"
88276,18919604,310,8701.0,04/01/2013 12:51,427,"Cheapside, Bank",04/01/2013 12:46,55,"Finsbury Circus, Liverpool Street"
88277,18896992,373,3915.0,02/01/2013 08:21,112,"Stonecutter Street, Holborn",02/01/2013 08:15,101,"Queen Street, Bank"
88278,18911293,443,2771.0,03/01/2013 08:35,112,"Stonecutter Street, Holborn",03/01/2013 08:28,421,"Southwark Station 2, Southwark"
88279,18933727,411,1057.0,04/01/2013 08:21,112,"Stonecutter Street, Holborn",04/01/2013 08:14,101,"Queen Street, Bank"
88280,18907019,734,8182.0,03/01/2013 20:07,261,"Princes Square, Bayswater",03/01/2013 19:54,373,"Prince Consort Road, Knightsbridge"
88281,18894063,1531,7228.0,02/01/2013 09:04,112,"Stonecutter Street, Holborn",02/01/2013 08:38,114,"Park Road (Baker Street), Regent's Park"
88282,18904214,1545,5599.0,03/01/2013 09:10,112,"Stonecutter Street, Holborn",03/01/2013 08:45,114,"Park Road (Baker Street), Regent's Park"
88283,18927725,1409,6014.0,04/01/2013 07:27,112,"Stonecutter Street, Holborn",04/01/2013 07:03,201,"Dorset Square, Marylebone"
88284,18891778,353,4475.0,02/01/2013 19:45,135,"Clerkenwell Green, Clerkenwell",02/01/2013 19:39,126,"Museum of London, Barbican"
88285,18903210,306,6230.0,03/01/2013 22:23,135,"Clerkenwell Green, Clerkenwell",03/01/2013 22:18,66,"Holborn Circus, Holborn"
88286,18927316,195,5979.0,04/01/2013 19:09,135,"Clerkenwell Green, Clerkenwell",04/01/2013 19:06,203,"West Smithfield Rotunda, Farringdon"
88287,18906970,308,8441.0,03/01/2013 22:24,135,"Clerkenwell Green, Clerkenwell",03/01/2013 22:18,66,"Holborn Circus, Holborn"
88288,18907285,248,3936.0,03/01/2013 18:04,135,"Clerkenwell Green, Clerkenwell",03/01/2013 18:00,203,"West Smithfield Rotunda, Farringdon"
88289,18883519,351,3830.0,02/01/2013 08:12,178,"Warwick Square, Pimlico",02/01/2013 08:06,291,"Claverton Street, Pimlico"
88290,18882899,297,8908.0,02/01/2013 14:28,178,"Warwick Square, Pimlico",02/01/2013 14:23,360,"Howick Place, Westminster"
88291,18947414,346,4667.0,05/01/2013 14:01,427,"Cheapside, Bank",05/01/2013 13:55,66,"Holborn Circus, Holborn"
88292,18951846,281,1048.0,05/01/2013 12:11,135,"Clerkenwell Green, Clerkenwell",05/01/2013 12:06,22,"Northington Street , Holborn"
88293,18939581,674,6526.0,04/01/2013 08:41,112,"Stonecutter Street, Holborn",04/01/2013 08:30,235,"Kennington Road , Vauxhall"
88294,18916462,772,1555.0,03/01/2013 08:19,112,"Stonecutter Street, Holborn",03/01/2013 08:06,235,"Kennington Road , Vauxhall"
88295,18888210,793,4969.0,02/01/2013 08:16,112,"Stonecutter Street, Holborn",02/01/2013 08:02,235,"Kennington Road , Vauxhall"
88296,18872025,358,224.0,01/01/2013 13:47,78,"Sadlers Sports Centre, Finsbury",01/01/2013 13:41,73,"Old Street Station, St. Luke's"
88297,18900921,574,5419.0,03/01/2013 21:49,201,"Dorset Square, Marylebone",03/01/2013 21:40,81,"Great Titchfield Street, Fitzrovia"
88298,18937327,392,3219.0,04/01/2013 22:36,112,"Stonecutter Street, Holborn",04/01/2013 22:30,227,"Great Percy Street, Clerkenwell"

In [2]:
data1.sample(frac=0.01)

,Rental Id,Duration,Bike Id,End Date,EndStation Id,EndStation Name,Start Date,StartStation Id,StartStation Name
33676,18924098,386,3970.0,04/01/2013 16:54,14,"Belgrove Street , King's Cross",04/01/2013 16:48,109,"Soho Square , Soho"
18075,18933479,276,2540.0,04/01/2013 13:29,537,"Old Montague Street, Whitechapel",04/01/2013 13:25,500,"Sidney Street, Stepney"
44837,18878887,635,7474.0,01/01/2013 08:07,512,"Pritchard's Road, Bethnal Green",01/01/2013 07:57,539,"Hoxton Station, Haggerston"
1199,18912091,504,3782.0,03/01/2013 11:02,39,"Shoreditch High Street, Shoreditch",03/01/2013 10:54,508,"Fournier Street, Whitechapel"
32673,18923255,158,6301.0,04/01/2013 07:15,157,"Wright's Lane, Kensington",04/01/2013 07:12,155,"Lexham Gardens, Kensington"
80994,18891522,420,758.0,02/01/2013 12:13,335,"Tavistock Street, Covent Garden",02/01/2013 12:06,364,"Alfred Place, Bloomsbury"
29006,18907750,446,2150.0,03/01/2013 20:39,30,"Windsor Terrace, Hoxton",03/01/2013 20:31,340,"Bank of England Museum, Bank"
87957,18897688,785,9097.0,02/01/2013 08:50,135,"Clerkenwell Green, Clerkenwell",02/01/2013 08:37,132,"Bethnal Green Road, Shoreditch"
14630,18908455,1156,1608.0,03/01/2013 19:07,42,"Wenlock Road , Hoxton",03/01/2013 18:48,205,"New Road 2, Whitechapel"
40844,18905401,1234,5793.0,03/01/2013 12:28,104,"Crosswall, Tower",03/01/2013 12:07,593,"Northdown Street, King's Cross"
57134,18957356,530,5141.0,05/01/2013 12:14,174,"Strand, Strand",05/01/2013 12:05,55,"Finsbury Circus, Liverpool Street"
43151,18879898,764,8069.0,01/01/2013 13:21,251,"Brushfield Street, Liverpool Street",01/01/2013 13:09,483,"Albert Gardens, Stepney"
73306,18903134,591,6911.0,03/01/2013 14:57,335,"Tavistock Street, Covent Garden",03/01/2013 14:47,22,"Northington Street , Holborn"
76656,18925310,1135,4983.0,04/01/2013 07:32,281,"Smith Square, Westminster",04/01/2013 07:13,16,"Cartwright Gardens , Bloomsbury"
61959,18950240,759,770.0,05/01/2013 20:31,440,"Kennington Oval, Oval",05/01/2013 20:18,272,"Baylis Road, Waterloo"
39747,18892748,111,5316.0,02/01/2013 16:47,2,"Phillimore Gardens, Kensington",02/01/2013 16:45,157,"Wright's Lane, Kensington"
55680,18941078,739,2539.0,04/01/2013 08:46,199,"Great Tower Street, Monument",04/01/2013 08:34,458,"Wapping Lane, Wapping"
28593,18934570,859,3896.0,04/01/2013 07:44,186,"South Wharf Road, Paddington",04/01/2013 07:30,167,"Eccleston Place, Victoria"
55041,18898135,2928,2090.0,03/01/2013 13:48,191,"Hyde Park Corner, Hyde Park",03/01/2013 12:59,111,"Park Lane , Hyde Park"
66257,18936656,-1357317508,718.0,01/01/1970 00:00,0,NaN,04/01/2013 16:38,552,"Watney Street, Shadwell"
11142,18899048,542,329.0,03/01/2013 19:00,131,"Eversholt Street , Camden Town",03/01/2013 18:51,6,"Broadcasting House, Marylebone"
67685,18891363,-1357153524,300.0,01/01/1970 00:00,0,NaN,02/01/2013 19:05,441,"Sail Street, Vauxhall"
7995,18935264,897,5221.0,04/01/2013 18:39,41,"Sun Street, Liverpool Street",04/01/2013 18:24,358,"High Holborn , Covent Garden"
9754,18871323,198,2269.0,01/01/2013 23:45,400,"George Street, Marylebone",01/01/2013 23:42,188,"Nutford Place, Marylebone"
16524,18940922,637,8989.0,04/01/2013 09:19,40,"Commercial Street, Shoreditch",04/01/2013 09:08,365,"City Road, Angel"
24041,18917639,424,6592.0,03/01/2013 17:56,217,"Wormwood Street, Liverpool Street",03/01/2013 17:49,194,"Hop Exchange, The Borough"
32708,18957014,652,3785.0,05/01/2013 13:34,323,"Clifton Street, Shoreditch",05/01/2013 13:23,365,"City Road, Angel"
14496,18891018,310,5403.0,02/01/2013 21:14,492,"The Green Bridge, Mile End",02/01/2013 21:09,531,"Twig Folly Bridge, Mile End"
14020,18927280,1070,5970.0,04/01/2013 17:59,104,"Crosswall, Tower",04/01/2013 17:42,108,"Abbey Orchard Street, Westminster"
65852,18899885,644,1019.0,03/01/2013 17:33,66,"Holborn Circus, Holborn",03/01/2013 17:22,175,"Appold Street, Liverpool Street"
...,...,...,...,...,...,...,...,...,...
77452,18895340,773,14.0,02/01/2013 20:32,295,"Swan Street, The Borough",02/01/2013 20:19,270,"Kennington Lane Rail Bridge, Vauxhall"
84179,18924155,438,1552.0,04/01/2013 08:59,112,"Stonecutter Street, Holborn",04/01/2013 08:52,194,"Hop Exchange, The Borough"
73876,18932397,489,5429.0,04/01/2013 07:05,55,"Finsbury Circus, Liverpool Street",04/01/2013 06:57,486,"Granby Street, Shoreditch"
18679,18932833,401,2818.0,04/01/2013 17:54,19,"Taviton Street, Bloomsbury",04/01/2013 17:48,311,"Foley Street, Fitzrovia"
30225,18895678,1116,8945.0,02/01/2013 18:17,73,"Old Street Station, St. Luke's",02/01/2013 17:59,381,"Charlotte Street, Fitzrovia"
22229,18915634,327,3363.0,04/01/2013 00:44,499,"Furze Green, Bow",04/01/2013 00:38,550,"Harford Street, Mile End"
33249,18937453,302,3471.0,04/01/2013 10:17,433,"Wren Street, Holborn",04/01/2013 10:11,12,"Malet Street, Bloomsbury"
35784,18910174,305,299.0,03/01/2013 13:09,340,"Bank of England Museum, Bank",03/01/2013 13:04,54,"Golden Lane, Barbican"
62300,18946792,13602,5486.0,06/01/2013 02:25,499,"Furze Green, Bow",05/01/2013 22:39,499,"Furze Green, Bow"
76838,18934307,708,7614.0,04/01/2013 08:21,109,"Soho Square , Soho",04/01/2013 08:09,14,"Belgrove Street , King's Cross"
59831,18935056,1455,8846.0,04/01/2013 15:00,111,"Park Lane , Hyde Park",04/01/2013 14:36,111,"Park Lane , Hyde Park"
60663,18945599,2663,3619.0,05/01/2013 18:54,334,"Concert Hall Approach 1, South Bank",05/01/2013 18:09,265,"Southwick Street, Paddington"
32480,18890745,313,5222.0,02/01/2013 08:10,104,"Crosswall, Tower",02/01/2013 08:05,449,"Shadwell Station, Shadwell"
8584,18889603,804,8178.0,02/01/2013 08:27,528,"Clarges Street, West End",02/01/2013 08:14,98,"Hampstead Road, Euston"
39802,18865347,3665,5399.0,01/01/2013 01:34,56,"Paddington Street, Marylebone",01/01/2013 00:33,439,"Killick Street, Kings Cross"
2782,18953074,831,2807.0,05/01/2013 22:48,356,"South Kensington Station, South Kensington",05/01/2013 22:34,151,"Chepstow Villas, Notting Hill"
67430,18883618,1346,6369.0,02/01/2013 13:56,381,"Charlotte Street, Fitzrovia",02/01/2013 13:34,457,"Castlehaven Road, Camden Town"
72422,18909375,510,9154.0,03/01/2013 13:36,272,"Baylis Road, Waterloo",03/01/2013 13:27,61,"Great Dover Street, Borough"
75367,18896705,1060,8387.0,02/01/2013 17:32,264,"Tysoe Street, Clerkenwell",02/01/2013 17:14,55,"Finsbury Circus, Liverpool Street"
80510,18899132,569,8528.0,03/01/2013 18:26,195,"Milroy Walk, South Bank",03/01/2013 18:16,427,"Cheapside, Bank"
13308,18933764,529,7526.0,04/01/2013 16:54,154,"Waterloo Station 3, Waterloo",04/01/2013 16:45,436,"Red Lion Street, Holborn"
9545,18945067,241,4253.0,05/01/2013 18:07,383,"Frith Street, Soho",05/01/2013 18:03,260,"Broadwick Street, Soho"
35964,18876312,128,7656.0,01/01/2013 10:48,356,"South Kensington Station, South Kensington",01/01/2013 10:45,428,"Exhibition Road, South Kensington"
28470,18956026,540,7349.0,05/01/2013 12:42,508,"Fournier Street, Whitechapel",05/01/2013 12:33,52,"Roscoe Street, St. Luke's"
68793,18903183,841,9078.0,03/01/2013 16:30,63,"Murray Grove , Hoxton",03/01/2013 16:16,18,"Drury Lane, Covent Garden"
16474,18907186,1809,3386.0,03/01/2013 17:37,220,"Chelsea Green, Chelsea",03/01/2013 17:07,65,"Gower Place , Euston"
78485,18958005,549,9192.0,05/01/2013 11:35,338,"Wellington Street , Strand",05/01/2013 11:26,310,"Black Prince Road, Vauxhall"
28977,18925123,307,1312.0,04/01/2013 18:15,101,"Queen Street, Bank",04/01/2013 18:10,55,"Finsbury Circus, Liverpool Street"
8267,18927311,790,7923.0,04/01/2013 18:01,325,"St. Martin's Street, West End",04/01/2013 17:48,313,"Wells Street, Fitzrovia"
12006,18895307,351,7441.0,02/01/2013 16:57,392,"Imperial College, Knightsbridge",02/01/2013 16:51,128,"Emperor's Gate, South Kensington"