In [1]:
import pandas as pd

datapath_2013 = 'Y:\\okofm\\tfl\\journey_data\\cyclehireusagestats-2013\\'

data1 = pd.read_csv(datapath_2013 + '1. Journey Data Extract 01Jan-05Jan13.csv')
data2 = pd.read_csv(datapath_2013 + '2. Journey Data Extract 06Jan-02Feb13.csv')

data = data1.append(data2)
data

#transform duration into minutes
data['Duration'] = data['Duration']/60
data

data1['day_of_week'] = pd.to_datetime(data1['Start Date'],format='%d/%m/%Y %H:%M').dt.dayofweek

days = {0:'Mon',1:'Tues',2:'Weds',3:'Thurs',4:'Fri',5:'Sat',6:'Sun'}

data1['day_of_week'] = data1['day_of_week'].apply(lambda x: days[x])

data1

,Rental Id,Duration,Bike Id,End Date,EndStation Id,EndStation Name,Start Date,StartStation Id,StartStation Name,day_of_week
0,18884041,271,4313.0,02/01/2013 13:32,251,"Brushfield Street, Liverpool Street",02/01/2013 13:28,509,"Fore Street, Guildhall",Weds
1,18905547,364,7755.0,03/01/2013 17:19,251,"Brushfield Street, Liverpool Street",03/01/2013 17:13,509,"Fore Street, Guildhall",Thurs
2,18941512,372,1193.0,04/01/2013 16:26,251,"Brushfield Street, Liverpool Street",04/01/2013 16:20,509,"Fore Street, Guildhall",Fri
3,18940395,1606,7163.0,04/01/2013 08:36,368,"Harriet Street, Knightsbridge",04/01/2013 08:10,62,"Cotton Garden Estate, Kennington",Fri
4,18944057,1352,4423.0,05/01/2013 16:58,386,"Moor Street, Soho",05/01/2013 16:36,144,"Kennington Cross, Kennington",Sat
5,18869989,1646,161.0,01/01/2013 11:51,329,"Prince Albert Road, Regent's Park",01/01/2013 11:24,326,"Graham Street, Angel",Tues
6,18873706,694,1673.0,01/01/2013 18:10,45,"Harewood Avenue, Marylebone",01/01/2013 17:59,116,"Little Argyll Street, West End",Tues
7,18925527,737,2799.0,04/01/2013 18:28,196,"Union Street, The Borough",04/01/2013 18:16,156,"New Kent Road, Borough",Fri
8,18944247,349,4124.0,05/01/2013 15:48,196,"Union Street, The Borough",05/01/2013 15:42,156,"New Kent Road, Borough",Sat
9,18945866,1679,7398.0,05/01/2013 17:57,2,"Phillimore Gardens, Kensington",05/01/2013 17:29,386,"Moor Street, Soho",Sat
10,18886658,378,6576.0,02/01/2013 19:07,196,"Union Street, The Borough",02/01/2013 19:01,156,"New Kent Road, Borough",Weds
11,18877625,1081,8124.0,01/01/2013 18:17,144,"Kennington Cross, Kennington",01/01/2013 17:59,116,"Little Argyll Street, West End",Tues
12,18879619,1077,7585.0,01/01/2013 11:54,159,"Great Marlborough Street, Soho",01/01/2013 11:36,86,"Sancroft Street, Vauxhall",Tues
13,18886440,857,4329.0,02/01/2013 08:25,159,"Great Marlborough Street, Soho",02/01/2013 08:11,86,"Sancroft Street, Vauxhall",Weds
14,18946752,818,861.0,05/01/2013 10:54,159,"Great Marlborough Street, Soho",05/01/2013 10:40,86,"Sancroft Street, Vauxhall",Sat
15,18905623,893,5625.0,03/01/2013 08:24,159,"Great Marlborough Street, Soho",03/01/2013 08:09,86,"Sancroft Street, Vauxhall",Thurs
16,18919033,1136,6849.0,03/01/2013 13:04,305,"Kennington Lane Tesco, Vauxhall",03/01/2013 12:46,159,"Great Marlborough Street, Soho",Thurs
17,18937761,932,8587.0,04/01/2013 08:23,159,"Great Marlborough Street, Soho",04/01/2013 08:08,86,"Sancroft Street, Vauxhall",Fri
18,18922728,2011,7554.0,04/01/2013 18:00,2,"Phillimore Gardens, Kensington",04/01/2013 17:27,225,"Notting Hill Gate Station, Notting Hill",Fri
19,18872324,672,6608.0,01/01/2013 06:49,546,"New Fetter Lane, Holborn",01/01/2013 06:38,295,"Swan Street, The Borough",Tues
20,18892341,672,4492.0,02/01/2013 07:02,546,"New Fetter Lane, Holborn",02/01/2013 06:51,295,"Swan Street, The Borough",Weds
21,18903687,692,3552.0,03/01/2013 06:48,546,"New Fetter Lane, Holborn",03/01/2013 06:36,295,"Swan Street, The Borough",Thurs
22,18921196,746,842.0,04/01/2013 06:54,546,"New Fetter Lane, Holborn",04/01/2013 06:41,295,"Swan Street, The Borough",Fri
23,18919901,987,3202.0,04/01/2013 15:25,194,"Hop Exchange, The Borough",04/01/2013 15:09,386,"Moor Street, Soho",Fri
24,18895284,498,671.0,02/01/2013 17:25,326,"Graham Street, Angel",02/01/2013 17:17,227,"Great Percy Street, Clerkenwell",Weds
25,18928454,518,2510.0,04/01/2013 13:41,67,"Hatton Garden, Holborn",04/01/2013 13:32,42,"Wenlock Road , Hoxton",Fri
26,18882692,352,1503.0,02/01/2013 07:52,101,"Queen Street, Bank",02/01/2013 07:46,78,"Sadlers Sports Centre, Finsbury",Weds
27,18905226,370,3464.0,03/01/2013 08:05,101,"Queen Street, Bank",03/01/2013 07:59,78,"Sadlers Sports Centre, Finsbury",Thurs
28,18928163,717,4341.0,04/01/2013 08:10,101,"Queen Street, Bank",04/01/2013 07:58,107,"Finsbury Leisure Centre, St. Luke's",Fri
29,18921055,1083,7672.0,04/01/2013 15:49,213,"Wellington Arch, Hyde Park",04/01/2013 15:31,133,"Derry Street, Kensington",Fri
...,...,...,...,...,...,...,...,...,...,...
88269,18912322,1883,7383.0,03/01/2013 19:40,301,"Marylebone Lane, Marylebone",03/01/2013 19:09,217,"Wormwood Street, Liverpool Street",Thurs
88270,18897326,570,5010.0,02/01/2013 07:38,221,"Horseferry Road, Westminster",02/01/2013 07:29,154,"Waterloo Station 3, Waterloo",Weds
88271,18910878,467,1174.0,03/01/2013 07:37,221,"Horseferry Road, Westminster",03/01/2013 07:29,154,"Waterloo Station 3, Waterloo",Thurs
88272,18936827,535,7375.0,04/01/2013 07:26,221,"Horseferry Road, Westminster",04/01/2013 07:18,154,"Waterloo Station 3, Waterloo",Fri
88273,18886255,601,8858.0,02/01/2013 19:40,161,"Guildhouse Street, Victoria",02/01/2013 19:30,233,"Pall Mall East, West End",Weds
88274,18910065,602,833.0,03/01/2013 08:16,95,"Aldersgate Street, Barbican",03/01/2013 08:06,154,"Waterloo Station 3, Waterloo",Thurs
88275,18940128,662,3258.0,04/01/2013 08:31,52,"Roscoe Street, St. Luke's",04/01/2013 08:20,154,"Waterloo Station 3, Waterloo",Fri
88276,18919604,310,8701.0,04/01/2013 12:51,427,"Cheapside, Bank",04/01/2013 12:46,55,"Finsbury Circus, Liverpool Street",Fri
88277,18896992,373,3915.0,02/01/2013 08:21,112,"Stonecutter Street, Holborn",02/01/2013 08:15,101,"Queen Street, Bank",Weds
88278,18911293,443,2771.0,03/01/2013 08:35,112,"Stonecutter Street, Holborn",03/01/2013 08:28,421,"Southwark Station 2, Southwark",Thurs
88279,18933727,411,1057.0,04/01/2013 08:21,112,"Stonecutter Street, Holborn",04/01/2013 08:14,101,"Queen Street, Bank",Fri
88280,18907019,734,8182.0,03/01/2013 20:07,261,"Princes Square, Bayswater",03/01/2013 19:54,373,"Prince Consort Road, Knightsbridge",Thurs
88281,18894063,1531,7228.0,02/01/2013 09:04,112,"Stonecutter Street, Holborn",02/01/2013 08:38,114,"Park Road (Baker Street), Regent's Park",Weds
88282,18904214,1545,5599.0,03/01/2013 09:10,112,"Stonecutter Street, Holborn",03/01/2013 08:45,114,"Park Road (Baker Street), Regent's Park",Thurs
88283,18927725,1409,6014.0,04/01/2013 07:27,112,"Stonecutter Street, Holborn",04/01/2013 07:03,201,"Dorset Square, Marylebone",Fri
88284,18891778,353,4475.0,02/01/2013 19:45,135,"Clerkenwell Green, Clerkenwell",02/01/2013 19:39,126,"Museum of London, Barbican",Weds
88285,18903210,306,6230.0,03/01/2013 22:23,135,"Clerkenwell Green, Clerkenwell",03/01/2013 22:18,66,"Holborn Circus, Holborn",Thurs
88286,18927316,195,5979.0,04/01/2013 19:09,135,"Clerkenwell Green, Clerkenwell",04/01/2013 19:06,203,"West Smithfield Rotunda, Farringdon",Fri
88287,18906970,308,8441.0,03/01/2013 22:24,135,"Clerkenwell Green, Clerkenwell",03/01/2013 22:18,66,"Holborn Circus, Holborn",Thurs
88288,18907285,248,3936.0,03/01/2013 18:04,135,"Clerkenwell Green, Clerkenwell",03/01/2013 18:00,203,"West Smithfield Rotunda, Farringdon",Thurs
88289,18883519,351,3830.0,02/01/2013 08:12,178,"Warwick Square, Pimlico",02/01/2013 08:06,291,"Claverton Street, Pimlico",Weds
88290,18882899,297,8908.0,02/01/2013 14:28,178,"Warwick Square, Pimlico",02/01/2013 14:23,360,"Howick Place, Westminster",Weds
88291,18947414,346,4667.0,05/01/2013 14:01,427,"Cheapside, Bank",05/01/2013 13:55,66,"Holborn Circus, Holborn",Sat
88292,18951846,281,1048.0,05/01/2013 12:11,135,"Clerkenwell Green, Clerkenwell",05/01/2013 12:06,22,"Northington Street , Holborn",Sat
88293,18939581,674,6526.0,04/01/2013 08:41,112,"Stonecutter Street, Holborn",04/01/2013 08:30,235,"Kennington Road , Vauxhall",Fri
88294,18916462,772,1555.0,03/01/2013 08:19,112,"Stonecutter Street, Holborn",03/01/2013 08:06,235,"Kennington Road , Vauxhall",Thurs
88295,18888210,793,4969.0,02/01/2013 08:16,112,"Stonecutter Street, Holborn",02/01/2013 08:02,235,"Kennington Road , Vauxhall",Weds
88296,18872025,358,224.0,01/01/2013 13:47,78,"Sadlers Sports Centre, Finsbury",01/01/2013 13:41,73,"Old Street Station, St. Luke's",Tues
88297,18900921,574,5419.0,03/01/2013 21:49,201,"Dorset Square, Marylebone",03/01/2013 21:40,81,"Great Titchfield Street, Fitzrovia",Thurs
88298,18937327,392,3219.0,04/01/2013 22:36,112,"Stonecutter Street, Holborn",04/01/2013 22:30,227,"Great Percy Street, Clerkenwell",Fri